syed updates

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -1,156 +1,266 @@
 version: '3'
 x-airflow-common:
   &airflow-common
-  image: apache/airflow:2.1.0
+  image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.5.1}
   environment:
-    - LOAD_EX=n
-    - POSTGRES_USER=airflow
-    - POSTGRES_PASSWORD=airflow
-    - POSTGRES_DB=airflow
-    - REDIS_HOST=redis
-    - REDIS_PASSWORD=redis
-    - AIRFLOW__SCHEDULER__STATSD_ON=True
-    - AIRFLOW__SCHEDULER__STATSD_HOST=statsd-exporter
-    - AIRFLOW__SCHEDULER__STATSD_PORT=8125
-    - AIRFLOW__SCHEDULER__STATSD_PREFIX=airflow
-    - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql://airflow:airflow@postgres/airflow
-    - AIRFLOW__CELERY__BROKER_URL=redis://:redis@redis:6379/1
-    - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@postgres/airflow
-    - AIRFLOW__CORE__FERNET_KEY=pMrhjIcqUNHMYRk_ZOBmMptWR6o1DahCXCKn5lEMpzM=
-    - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
-    - AIRFLOW_HOME=/opt/airflow
-    - AIRFLOW_CONFIG=/opt/airflow/airflow.cfg
-    - AIRFLOW__CORE__LOAD_EXAMPLES=False
-    - AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS=False
-    - AIRFLOW__WEBSERVER__WORKERS=2
-    - AIRFLOW__WEBSERVER__WORKER_REFRESH_INTERVAL=1800
+    &airflow-common-env
+    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
+    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
+    # For backward compatibility, with Airflow <2.3
+    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
+    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
+    AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
+    AIRFLOW__CORE__FERNET_KEY: ''
+    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
+    AIRFLOW__CORE__LOAD_EXAMPLES: 'true'
+    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'
+    _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS:-}
   volumes:
-    - ./dags:/opt/airflow/dags/
-    - ./airflow.cfg:/opt/airflow/airflow.cfg
-    - ./airflow-data/logs:/opt/airflow/logs
-    - ./airflow-data/plugins:/opt/airflow/plugins
+    - ${AIRFLOW_PROJ_DIR:-.}/dags:/opt/airflow/dags
+    - ${AIRFLOW_PROJ_DIR:-.}/logs:/opt/airflow/logs
+    - ${AIRFLOW_PROJ_DIR:-.}/plugins:/opt/airflow/plugins
+  user: "${AIRFLOW_UID:-50000}:0"
+  depends_on:
+    &airflow-common-depends-on
+    redis:
+      condition: service_healthy
+    postgres:
+      condition: service_healthy
 
 services:
-    airflow-init:
-        << : *airflow-common
-        container_name: airflow-init
-        entrypoint: /bin/bash
-        command:
-        - -c
-        - airflow users list || ( airflow db init &&
-            airflow users create
-            --role Admin
-            --username admin
-            --password password
-            --email airflow@airflow.com
-            --firstname first
-            --lastname last )
-        restart: on-failure
+  postgres:
+    image: postgres:13
+    environment:
+      POSTGRES_USER: airflow
+      POSTGRES_PASSWORD: airflow
+      POSTGRES_DB: airflow
+    volumes:
+      - postgres-db-volume:/var/lib/postgresql/data
+    healthcheck:
+      test: ["CMD", "pg_isready", "-U", "airflow"]
+      interval: 5s
+      retries: 5
+    restart: always
 
-    redis:
-        container_name: airflow-redis
-        image: 'redis:5.0.5'
-        depends_on:
-            - statsd-exporter
-        command: redis-server --requirepass redis
-        ports:
-            - 6380:6379
+  redis:
+    image: redis:latest
+    expose:
+      - 6379
+    healthcheck:
+      test: ["CMD", "redis-cli", "ping"]
+      interval: 5s
+      timeout: 30s
+      retries: 50
+    restart: always
 
-    postgres:
-        container_name: airflow-postgres
-        image: postgres:9.6
-        depends_on:
-            - statsd-exporter
-        environment:
-            - POSTGRES_USER=airflow
-            - POSTGRES_PASSWORD=airflow
-            - POSTGRES_DB=airflow
+  airflow-webserver:
+    <<: *airflow-common
+    command: webserver
+    ports:
+      - 8080:8080
+    healthcheck:
+      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
+      interval: 10s
+      timeout: 10s
+      retries: 5
+    restart: always
+    depends_on:
+      <<: *airflow-common-depends-on
+      airflow-init:
+        condition: service_completed_successfully
 
-    webserver:
-        << : *airflow-common
-        container_name: airflow-webserver
-        restart: always
-        depends_on:
-            - postgres
-            - redis
-            - statsd-exporter
-            - airflow-init
-        ports:
-            - "8080:8080"
-        command: airflow webserver
-        healthcheck:
-            test: ["CMD-SHELL", "[ -f /opt/airflow/airflow-webserver.pid ]"]
-            interval: 30s
-            timeout: 30s
-            retries: 3
+  airflow-scheduler:
+    <<: *airflow-common
+    command: scheduler
+    healthcheck:
+      test: ["CMD-SHELL", 'airflow jobs check --job-type SchedulerJob --hostname "$${HOSTNAME}"']
+      interval: 10s
+      timeout: 10s
+      retries: 5
+    restart: always
+    depends_on:
+      <<: *airflow-common-depends-on
+      airflow-init:
+        condition: service_completed_successfully
 
-    flower:
-        << : *airflow-common
-        container_name: airflow-flower
-        restart: always
-        depends_on:
-            - redis
-            - statsd-exporter
-            - airflow-init
-        ports:
-            - "5555:5555"
-        command: airflow celery flower
+  airflow-worker:
+    <<: *airflow-common
+    command: celery worker
+    healthcheck:
+      test:
+        - "CMD-SHELL"
+        - 'celery --app airflow.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"'
+      interval: 10s
+      timeout: 10s
+      retries: 5
+    environment:
+      <<: *airflow-common-env
+      # Required to handle warm shutdown of the celery workers properly
+      # See https://airflow.apache.org/docs/docker-stack/entrypoint.html#signal-propagation
+      DUMB_INIT_SETSID: "0"
+    restart: always
+    depends_on:
+      <<: *airflow-common-depends-on
+      airflow-init:
+        condition: service_completed_successfully
 
-    scheduler:
-        << : *airflow-common
-        container_name: airflow-scheduler
-        restart: always
-        depends_on:
-            - postgres
-            - webserver
-            - airflow-init
-        command: airflow scheduler
+  airflow-triggerer:
+    <<: *airflow-common
+    command: triggerer
+    healthcheck:
+      test: ["CMD-SHELL", 'airflow jobs check --job-type TriggererJob --hostname "$${HOSTNAME}"']
+      interval: 10s
+      timeout: 10s
+      retries: 5
+    restart: always
+    depends_on:
+      <<: *airflow-common-depends-on
+      airflow-init:
+        condition: service_completed_successfully
 
-    worker:
-        << : *airflow-common
-        container_name: airflow-worker
-        restart: always
-        sysctls:
-            - net.ipv4.tcp_keepalive_time=200
-            - net.ipv4.tcp_keepalive_intvl=200
-            - net.ipv4.tcp_keepalive_probes=5
-        depends_on:
-            - redis
-            - scheduler
-            - airflow-init
-        ports:
-            - "8793"
-        command: airflow celery worker
+  airflow-init:
+    <<: *airflow-common
+    entrypoint: /bin/bash
+    # yamllint disable rule:line-length
+    command:
+      - -c
+      - |
+        function ver() {
+          printf "%04d%04d%04d%04d" $${1//./ }
+        }
+        airflow_version=$$(AIRFLOW__LOGGING__LOGGING_LEVEL=INFO && gosu airflow airflow version)
+        airflow_version_comparable=$$(ver $${airflow_version})
+        min_airflow_version=2.2.0
+        min_airflow_version_comparable=$$(ver $${min_airflow_version})
+        if (( airflow_version_comparable < min_airflow_version_comparable )); then
+          echo
+          echo -e "\033[1;31mERROR!!!: Too old Airflow version $${airflow_version}!\e[0m"
+          echo "The minimum Airflow version supported: $${min_airflow_version}. Only use this or higher!"
+          echo
+          exit 1
+        fi
+        if [[ -z "${AIRFLOW_UID}" ]]; then
+          echo
+          echo -e "\033[1;33mWARNING!!!: AIRFLOW_UID not set!\e[0m"
+          echo "If you are on Linux, you SHOULD follow the instructions below to set "
+          echo "AIRFLOW_UID environment variable, otherwise files will be owned by root."
+          echo "For other operating systems you can get rid of the warning with manually created .env file:"
+          echo "    See: https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#setting-the-right-airflow-user"
+          echo
+        fi
+        one_meg=1048576
+        mem_available=$$(($$(getconf _PHYS_PAGES) * $$(getconf PAGE_SIZE) / one_meg))
+        cpus_available=$$(grep -cE 'cpu[0-9]+' /proc/stat)
+        disk_available=$$(df / | tail -1 | awk '{print $$4}')
+        warning_resources="false"
+        if (( mem_available < 4000 )) ; then
+          echo
+          echo -e "\033[1;33mWARNING!!!: Not enough memory available for Docker.\e[0m"
+          echo "At least 4GB of memory required. You have $$(numfmt --to iec $$((mem_available * one_meg)))"
+          echo
+          warning_resources="true"
+        fi
+        if (( cpus_available < 2 )); then
+          echo
+          echo -e "\033[1;33mWARNING!!!: Not enough CPUS available for Docker.\e[0m"
+          echo "At least 2 CPUs recommended. You have $${cpus_available}"
+          echo
+          warning_resources="true"
+        fi
+        if (( disk_available < one_meg * 10 )); then
+          echo
+          echo -e "\033[1;33mWARNING!!!: Not enough Disk space available for Docker.\e[0m"
+          echo "At least 10 GBs recommended. You have $$(numfmt --to iec $$((disk_available * 1024 )))"
+          echo
+          warning_resources="true"
+        fi
+        if [[ $${warning_resources} == "true" ]]; then
+          echo
+          echo -e "\033[1;33mWARNING!!!: You have not enough resources to run Airflow (see above)!\e[0m"
+          echo "Please follow the instructions to increase amount of resources available:"
+          echo "   https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#before-you-begin"
+          echo
+        fi
+        mkdir -p /sources/logs /sources/dags /sources/plugins
+        chown -R "${AIRFLOW_UID}:0" /sources/{logs,dags,plugins}
+        exec /entrypoint airflow version
+    # yamllint enable rule:line-length
+    environment:
+      <<: *airflow-common-env
+      _AIRFLOW_DB_UPGRADE: 'true'
+      _AIRFLOW_WWW_USER_CREATE: 'true'
+      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
+      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
+      _PIP_ADDITIONAL_REQUIREMENTS: ''
+    user: "0:0"
+    volumes:
+      - ${AIRFLOW_PROJ_DIR:-.}:/sources
 
-    statsd-exporter:
-        image: prom/statsd-exporter
-        container_name: airflow-statsd-exporter
-        command: "--statsd.listen-udp=:8125 --web.listen-address=:9102"
-        ports:
-            - 9123:9102
-            - 8125:8125/udp
-    
-    prometheus:
-        image: prom/prometheus
-        container_name: airflow-prometheus
-        user: "0"
-        ports:
-            - 9090:9090
-        volumes:
-            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
-            - ./prometheus/volume:/prometheus
-        
-    grafana:
-        image: grafana/grafana:7.1.5
-        container_name: airflow-grafana
-        environment:
-            GF_SECURITY_ADMIN_USER: admin
-            GF_SECURITY_ADMIN_PASSWORD: password
-            GF_PATHS_PROVISIONING: /grafana/provisioning
-        ports:
-            - 3000:3000
-        volumes:
-            - ./grafana/volume/data:/grafana
-            - ./grafana/volume/datasources:/grafana/datasources
-            - ./grafana/volume/dashboards:/grafana/dashboards
-            - ./grafana/volume/provisioning:/grafana/provisioning
+  airflow-cli:
+    <<: *airflow-common
+    profiles:
+      - debug
+    environment:
+      <<: *airflow-common-env
+      CONNECTION_CHECK_MAX_COUNT: "0"
+    # Workaround for entrypoint issue. See: https://github.com/apache/airflow/issues/16252
+    command:
+      - bash
+      - -c
+      - airflow
+
+  # You can enable flower by adding "--profile flower" option e.g. docker-compose --profile flower up
+  # or by explicitly targeted on the command line e.g. docker-compose up flower.
+  # See: https://docs.docker.com/compose/profiles/
+  flower:
+    <<: *airflow-common
+    command: celery flower
+    profiles:
+      - flower
+    ports:
+      - 5555:5555
+    healthcheck:
+      test: ["CMD", "curl", "--fail", "http://localhost:5555/"]
+      interval: 10s
+      timeout: 10s
+      retries: 5
+    restart: always
+    depends_on:
+      <<: *airflow-common-depends-on
+      airflow-init:
+        condition: service_completed_successfully
+
+  statsd-exporter:
+    image: prom/statsd-exporter
+    container_name: airflow-statsd-exporter
+    command: "--statsd.listen-udp=:8125 --web.listen-address=:9102"
+    ports:
+        - 9123:9102
+        - 8125:8125/udp
+
+  prometheus:
+    image: prom/prometheus
+    container_name: airflow-prometheus
+    user: "0"
+    ports:
+        - 9090:9090
+    volumes:
+        - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
+        - ./prometheus/volume:/prometheus
+
+  grafana:
+    image: grafana/grafana:7.1.5
+    container_name: airflow-grafana
+    environment:
+        GF_SECURITY_ADMIN_USER: admin
+        GF_SECURITY_ADMIN_PASSWORD: password
+        GF_PATHS_PROVISIONING: /grafana/provisioning
+    ports:
+        - 3000:3000
+    volumes:
+        - ./grafana/volume/data:/grafana
+        - ./grafana/volume/datasources:/grafana/datasources
+        - ./grafana/volume/dashboards:/grafana/dashboards
+        - ./grafana/volume/provisioning:/grafana/provisioning
+volumes:
+  postgres-db-volume:
